server:
  port: 8888

spring:
  application:
    name: instagram

  datasource:
    url: jdbc:h2:./db/microgram;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true

  output:
    ansi:
      enabled: always

  security:
    user:
      name: email
      password: password

  freemarker:
    expose-session-attributes: true
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    root: info
    org:
      springframework:
        security: debug

  file:
    name: logs/spring.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7